FROM docker.io/n8nio/n8n:latest

# Alternar para root para instalar binário estático do FFmpeg
USER root

# Baixar binário estático oficial do FFmpeg (funciona em qualquer distro Linux x86_64)
RUN wget -q https://johnvansickle.com/ffmpeg/releases/ffmpeg-release-amd64-static.tar.xz && \
    tar -xf ffmpeg-release-amd64-static.tar.xz && \
    mv ffmpeg-*-amd64-static/ffmpeg /usr/local/bin/ && \
    mv ffmpeg-*-amd64-static/ffprobe /usr/local/bin/ && \
    rm -rf ffmpeg*

# Criar pasta /data com permissões para o usuário node
RUN mkdir -p /data && chown -R node:node /data

# Retornar para o usuário node
USER node



