version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Containerfile
    container_name: pipelineface_web_app
    restart: unless-stopped
    network_mode: "host"
    environment:
      - MONGO_URI=mongodb://localhost:27017
      - WHISPER_URL=http://localhost:9000/asr
      - OLLAMA_URL=http://localhost:11434/api/chat
    volumes:
      - .:/app

  mongodb:
    image: mongo:7.0
    container_name: pipelineface_mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  whisper:
    image: docker.io/onerahmet/openai-whisper-asr-webservice:latest
    container_name: pipelineface_whisper
    restart: unless-stopped
    ports:
      - "9000:9000"
    environment:
      - ASR_MODEL=base

  scraper:
    build:
      context: ./scraper
      dockerfile: Containerfile
    container_name: pipelineface_scraper
    restart: unless-stopped
    network_mode: "host"
    entrypoint: ["tail", "-f", "/dev/null"]
    volumes:
      - .:/app

volumes:
  mongo-data:
