version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Containerfile
    container_name: pipelineface_web_app
    restart: unless-stopped
    network_mode: "host"
    environment:
      - MONGO_URI=mongodb://localhost:27017
      - WHISPER_URL=http://localhost:9000/asr
      - OLLAMA_URL=http://localhost:11434/api/chat
    volumes:
      - ./data:/app/data

  mongodb:
    image: mongo:7.0
    container_name: pipelineface_mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
